codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "80...100"

  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: true
